
task: classification
metric: accuracy
distribute: False
debug: True
save_dir: /storage_labs/3030/LyginE/projects/paradigma/experiments/framework_tests/newrun
device:
    cuda: [1]
model: 
    name: resnet 
    version: '18'
    source: pytorch
dataset:
    annotation: /storage_labs/db/face_masks/dataset_mask_face_640_480.csv
    train_transform: 
        - totensor
        - randomrotation: 
            - [-5, 5]
        - randomresizedcrop:
            - 224
            - [0.8, 1.0]
        - randomhorizontalflip
        - randomverticalflip
        - normalize: 
            - mean: [0.485, 0.456, 0.406]
            - std: [0.229, 0.224, 0.225]
    val_transform:
        - totensor
        - resize: 256
        - centercrop: 224
        - normalize: 
            - mean: [0.485, 0.456, 0.406]
            - std: [0.229, 0.224, 0.225]
loader:
    workers: 8
    shuffle: True
    drop_last: True
    batch_size: 64
experiments:  
    train:
        timing: True
        train_function:
            path: /storage_labs/3030/LyginE/projects/paradigma/quant_framework_new/base/learning/train.py
            name: train_
        val_function:
            path: /storage_labs/3030/LyginE/projects/paradigma/quant_framework_new/base/learning/validate.py
            name: validate_
        optimizer: 
            name: Adam
            parameters: 
                lr: 0.5
        scheduler: 
            name: reducelronplateau
            parameters: 
                factor: 0.5
                patirnce: 10
                threshold: 0.001
        loss :
            name: crossentropyloss
        epochs: 300
        val_epoch: 10
    
    quantize:    
        train_function:
            path: /storage_labs/3030/LyginE/projects/paradigma/quant_framework_new/base/learning/train.py
            name: train_
        val_function:
            path: /storage_labs/3030/LyginE/projects/paradigma/quant_framework_new/base/learning/validate.py
            name: validate_
        optimizer: 
            name: Adam
            parameters: 
                lr: 0.5
        loss :
            name: crossentropyloss
        scheduler: 
            name: reducelronplateau
            parameters: 
                factor: 0.75
                patience: 5
                threshold: 0.001
        mode: qat
        engine: qnnpack
        epochs: 100
        val_epoch: 5      


log:
    level: info
    name: 
    output:
        file:
            out: default
            messageformat: "%(asctime)s | %(levelname)s %(message)s"
            dateformat: '%Y-%m-%d %H:%M:%S'
        console:
            out: default
            messageformat: "%(asctime)s | %(levelname)s %(message)s"
            dateformat: '%Y-%m-%d %H:%M:%S'     